import os
import warnings
from contextlib import contextmanager

import psycopg
from psycopg_pool import ConnectionPool

_DEFAULT_PASSWORD = "Postobon12.1"


def _build_conninfo() -> str:
    """Build connection string from env vars with fallback defaults."""
    password = os.getenv("DB_PASSWORD")
    if not password:
        warnings.warn(
            "DB_PASSWORD no definida. Usando valor por defecto (inseguro). "
            "Configúrala como variable de entorno.",
            RuntimeWarning,
            stacklevel=2,
        )
        password = _DEFAULT_PASSWORD

    return (
        f"host={os.getenv('DB_HOST', 'localhost')} "
        f"port={os.getenv('DB_PORT', '5432')} "
        f"dbname={os.getenv('DB_NAME', 'postgres')} "
        f"user={os.getenv('DB_USER', 'postgres')} "
        f"password={password}"
    )


class Database:

    def __init__(self):
        self.pool = ConnectionPool(
            conninfo=_build_conninfo(),
            min_size=1,
            max_size=10,
        )
        self._ensure_schema()

    def _ensure_schema(self):
        """Create required tables if they do not exist (auto-migration)."""
        ddl = """
            CREATE TABLE IF NOT EXISTS public.services (
                id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                name character varying(150) NOT NULL,
                description text DEFAULT ''::text,
                price numeric(12,2) DEFAULT 0,
                icon character varying(50) DEFAULT '🚀'::character varying,
                accent_color character varying(20) DEFAULT '#3B82F6'::character varying,
                is_active boolean DEFAULT true,
                PRIMARY KEY (id)
            );

            INSERT INTO public.services (name, description, price)
            SELECT 'Matrícula Anual', 'Cobertura anual de matrícula', 50000
            WHERE NOT EXISTS (SELECT 1 FROM public.services WHERE name = 'Matrícula Anual');

            INSERT INTO public.services (name, description, price)
            SELECT 'Clase Personalizada', 'Clase uno a uno con instructor', 45000
            WHERE NOT EXISTS (SELECT 1 FROM public.services WHERE name = 'Clase Personalizada');

            INSERT INTO public.services (name, description, price)
            SELECT 'Examen de Ascenso', 'Evaluación para cambio de cinturón', 25000
            WHERE NOT EXISTS (SELECT 1 FROM public.services WHERE name = 'Examen de Ascenso');
        """
        conn = None
        try:
            conn = self.pool.getconn()
            conn.autocommit = True
            cur = conn.cursor()
            try:
                cur.execute(ddl)
            finally:
                cur.close()
        except Exception as e:
            import warnings
            warnings.warn(f"Schema initialization failed: {e}", RuntimeWarning, stacklevel=2)
        finally:
            if conn:
                self.pool.putconn(conn)

    def get_conn(self):
        return self.pool.getconn()

    def release(self, conn):
        self.pool.putconn(conn)

    @contextmanager
    def cursor(self):
        """Context manager yielding a cursor (read-only, no commit)."""
        conn = self.get_conn()
        try:
            conn.autocommit = True
            cur = conn.cursor()
            try:
                yield cur
            finally:
                cur.close()
        finally:
            self.release(conn)

    @contextmanager
    def transaction(self):
        """Context manager yielding a cursor with commit/rollback."""
        conn = self.get_conn()
        cur = None
        try:
            cur = conn.cursor()
            yield cur
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            if cur is not None:
                cur.close()
            self.release(conn)


    def run_sql_file(self, filepath: str):
        """Execute a SQL file in a single transaction. Idempotent."""
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                sql = f.read()
            with self.transaction() as cur:
                cur.execute(sql)
            import warnings
            warnings.warn(f"Migration executed: {filepath}", RuntimeWarning, stacklevel=2)
        except Exception as e:
            import warnings
            warnings.warn(
                f"Migration failed ({filepath}): {e}",
                RuntimeWarning,
                stacklevel=2,
            )


db = Database()