-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.roles
(
    id integer NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.people
(
    id integer NOT NULL DEFAULT nextval('people_id_seq'::regclass),
    first_name character varying(100) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    birthdate date,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT people_pkey PRIMARY KEY (id),
    CONSTRAINT people_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    id_person integer NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_id_person_key UNIQUE (id_person),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.roles_people
(
    roles_id integer NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
    people_id integer NOT NULL DEFAULT nextval('people_id_seq'::regclass)
);

CREATE TABLE IF NOT EXISTS public.students
(
    id integer NOT NULL DEFAULT nextval('students_id_seq'::regclass),
    id_person integer,
    id_type_document integer,
    document character varying(50) COLLATE pg_catalog."default",
    category_id integer,
    id_status integer,
    CONSTRAINT students_pkey PRIMARY KEY (id),
    CONSTRAINT students_id_person_key UNIQUE (id_person)
);

CREATE TABLE IF NOT EXISTS public.type_document
(
    id bigint NOT NULL DEFAULT nextval('type_document_id_seq'::regclass),
    type_document character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT type_document_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.status
(
    id bigint NOT NULL DEFAULT nextval('status_id_seq'::regclass),
    status character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT status_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.belts
(
    id bigint NOT NULL DEFAULT nextval('belts_id_seq'::regclass),
    name character varying(75) COLLATE pg_catalog."default" NOT NULL,
    id_martial_art integer NOT NULL,
    orden integer NOT NULL,
    CONSTRAINT belts_pkey PRIMARY KEY (id),
    CONSTRAINT belts_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.belts_students
(
    belts_id bigint NOT NULL DEFAULT nextval('belts_id_seq'::regclass),
    students_id integer NOT NULL DEFAULT nextval('students_id_seq'::regclass)
);

CREATE TABLE IF NOT EXISTS public.students_belts_history
(
    id integer NOT NULL DEFAULT nextval('students_belts_history_id_seq'::regclass),
    id_student integer,
    id_belt integer,
    action character varying(20) COLLATE pg_catalog."default",
    date_changed timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT students_belts_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.martial_arts
(
    id integer NOT NULL DEFAULT nextval('martial_arts_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT martial_arts_pkey PRIMARY KEY (id),
    CONSTRAINT martial_arts_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.schedule
(
    id integer NOT NULL DEFAULT nextval('schedule_id_seq'::regclass),
    id_martial_art integer,
    name character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT schedule_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.instructors
(
    id integer NOT NULL DEFAULT nextval('instructors_id_seq'::regclass),
    id_person integer,
    CONSTRAINT instructors_pkey PRIMARY KEY (id),
    CONSTRAINT instructors_id_person_key UNIQUE (id_person)
);

CREATE TABLE IF NOT EXISTS public.classes
(
    id integer NOT NULL DEFAULT nextval('classes_id_seq'::regclass),
    id_schedule integer,
    id_instructor integer,
    date date,
    CONSTRAINT classes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.movement_type
(
    id integer NOT NULL DEFAULT nextval('movement_type_id_seq'::regclass),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT movement_type_pkey PRIMARY KEY (id),
    CONSTRAINT movement_type_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.account_movements
(
    id integer NOT NULL DEFAULT nextval('account_movements_id_seq'::regclass),
    id_destination_account integer NOT NULL,
    id_movement_type integer NOT NULL,
    amount numeric(12, 2) NOT NULL,
    payment_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT account_movements_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.destination_account
(
    id integer NOT NULL DEFAULT nextval('destination_account_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    account_number integer NOT NULL,
    CONSTRAINT destination_account_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.expense_categories
(
    id integer NOT NULL DEFAULT nextval('expense_categories_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT expense_categories_pkey PRIMARY KEY (id),
    CONSTRAINT expense_categories_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.expenses
(
    id integer NOT NULL DEFAULT nextval('expenses_id_seq'::regclass),
    id_expense_category integer NOT NULL,
    id_destination_account integer NOT NULL,
    amount numeric(12, 2) NOT NULL,
    expense_date date NOT NULL,
    description text COLLATE pg_catalog."default",
    invoice_number character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT expenses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    id integer NOT NULL DEFAULT nextval('payments_id_seq'::regclass),
    id_person integer NOT NULL,
    total numeric(12, 2) NOT NULL,
    total_paid numeric(12, 2) NOT NULL,
    payment_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_payment_method integer NOT NULL,
    id_destination_account integer NOT NULL,
    description text COLLATE pg_catalog."default",
    note text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.type_products
(
    id integer NOT NULL DEFAULT nextval('type_products_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT type_products_pkey PRIMARY KEY (id),
    CONSTRAINT type_products_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.payment_method
(
    id integer NOT NULL DEFAULT nextval('payment_method_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT payment_method_pkey PRIMARY KEY (id),
    CONSTRAINT payment_method_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.payment_items
(
    id integer NOT NULL DEFAULT nextval('payment_items_id_seq'::regclass),
    id_payments integer NOT NULL,
    id_product integer,
    id_membership_plan integer,
    quantity integer NOT NULL DEFAULT 1,
    unit_price numeric(12, 2) NOT NULL,
    subtotal numeric(12, 2) NOT NULL,
    CONSTRAINT payment_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id integer NOT NULL DEFAULT nextval('products_id_seq'::regclass),
    id_type_product integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    sale_price numeric(12, 2) NOT NULL,
    stock integer NOT NULL DEFAULT 0,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.membership_plans
(
    id integer NOT NULL DEFAULT nextval('membership_plans_id_seq'::regclass),
    id_type_product integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    monthly_fee numeric(12, 2) NOT NULL,
    discount numeric(12, 2) DEFAULT 0,
    discount_by_person boolean DEFAULT false,
    classes_per_week integer NOT NULL,
    CONSTRAINT membership_plans_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student_memberships
(
    id integer NOT NULL DEFAULT nextval('student_memberships_id_seq'::regclass),
    id_student integer NOT NULL,
    id_membership_plan integer NOT NULL,
    custom_fee numeric(12, 2),
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date,
    CONSTRAINT student_memberships_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.users
    ADD FOREIGN KEY (id_person)
    REFERENCES public.people (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.roles_people
    ADD FOREIGN KEY (roles_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.roles_people
    ADD FOREIGN KEY (people_id)
    REFERENCES public.people (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.roles_people
    ADD FOREIGN KEY (people_id)
    REFERENCES public.students (id_person) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.roles_people
    ADD FOREIGN KEY (people_id)
    REFERENCES public.instructors (id_person) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.type_document
    ADD FOREIGN KEY (id)
    REFERENCES public.students (id_type_document) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.status
    ADD FOREIGN KEY (id)
    REFERENCES public.students (id_status) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.belts
    ADD FOREIGN KEY (id_martial_art)
    REFERENCES public.martial_arts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.belts_students
    ADD FOREIGN KEY (belts_id)
    REFERENCES public.belts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.belts_students
    ADD FOREIGN KEY (students_id)
    REFERENCES public.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.students_belts_history
    ADD FOREIGN KEY (id_student)
    REFERENCES public.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.students_belts_history
    ADD FOREIGN KEY (id_belt)
    REFERENCES public.belts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.schedule
    ADD FOREIGN KEY (id_martial_art)
    REFERENCES public.martial_arts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.classes
    ADD FOREIGN KEY (id_schedule)
    REFERENCES public.schedule (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.classes
    ADD FOREIGN KEY (id_instructor)
    REFERENCES public.instructors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.account_movements
    ADD FOREIGN KEY (id_movement_type)
    REFERENCES public.movement_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.account_movements
    ADD FOREIGN KEY (id_destination_account)
    REFERENCES public.destination_account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.expenses
    ADD FOREIGN KEY (id_expense_category)
    REFERENCES public.expense_categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.expenses
    ADD FOREIGN KEY (id_destination_account)
    REFERENCES public.destination_account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.payments
    ADD FOREIGN KEY (id_person)
    REFERENCES public.people (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.payments
    ADD FOREIGN KEY (id_destination_account)
    REFERENCES public.destination_account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.payments
    ADD FOREIGN KEY (id_payment_method)
    REFERENCES public.payment_method (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.payment_items
    ADD FOREIGN KEY (id_product)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.payment_items
    ADD FOREIGN KEY (id_payments)
    REFERENCES public.payments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.payment_items
    ADD FOREIGN KEY (id_membership_plan)
    REFERENCES public.membership_plans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (id_type_product)
    REFERENCES public.type_products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.student_memberships
    ADD FOREIGN KEY (id_student)
    REFERENCES public.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.student_memberships
    ADD FOREIGN KEY (id_membership_plan)
    REFERENCES public.membership_plans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;